### ISSUE TITLE
New project: MyProject

### ISSUE THREAD

**Issue by zhaoyanpeng** [allenai/allennlp-gallery#23]
Project metadata:
```
{
  "title": "Unsupervised Transfer of Semantic Role Models from Verbal to Nominal Domain",
  "authors": [
    {
      "name": "Yanpeng Zhao",
      "email": "yanp.zhao@ed.ac.uk",
      "affiliation": "University of Edinburgh",
      "google_scholar_author_page": "https://scholar.google.com/citations?user=-T9FigIAAAAJ",
    }, {
      "name": "Ivan Titov",
      "email": "ititov@inf.ed.ac.uk",
      "affiliation": "University of Edinburgh & University of Amsterdam",
      "google_scholar_author_page": "https://scholar.google.com/citations?user=FKUc3vsAAAAJ",
    }
  ],
  "submission_date": "2020-09-26",
  "github_link": "https://github.com/zhaoyanpeng/srltransfer",
  "paper_link": "https://arxiv.org/abs/2005.00278",
  "allennlp_version": "0.8.2",
  "datasets": [
    {
      "name": "srl_v2n",
      "link": "https://github.com/zhaoyanpeng/srltransfer"
    }
  ],
  "tags": ["transfer learning", "semantic role labeling"]
}
```

Description:

We investigate a transfer scenario where we assume role-annotated data for the source verbal domain but only unlabeled data for the target nominal domain. Our key assumption, enabling the transfer between the two domains, is that selectional preferences of a role (i.e., preferences or constraints on the admissible arguments) do not strongly depend on whether the relation is triggered by a verb or a noun. For example, the same set of arguments can fill the Acquirer role for the verbal predicate `acquire` and its nominal form `acquisition`. We approach the transfer task from the variational autoencoding perspective.

**Comment by dirkgr** [comment]
This is great! I hope the problem you needed to fix with a patch has since been fixed in the regular version of AllenNLP?

**Comment by zhaoyanpeng** [comment]
Yeah, I opened an issue and it was fixed immediately.
