### ISSUE TITLE
New project: SmBop

### ISSUE THREAD

**Issue by OhadRubin** [allenai/allennlp-gallery#40]
Project metadata:
```
{
  "title": "SmBoP: Semi-autoregressive Bottom-up Semantic Parsing",
  "authors": [
    {
      "name": "Ohad Rubin",
      "email": "ohadr@mail.tau.ac.il",
      "twitter": "@OhadRubin",
      "affiliation": "Tel Aviv University",
      "google_scholar_author_page": "https://scholar.google.com/citations?user=4p8NquAAAAAJ",
      "s2_author_page": "https://www.semanticscholar.org/author/Ohad-Rubin/2001128224",
    }, {
      "name": "Jonathan Berant",
      "twitter": "@JonathanBerant",
      "email": "joberant@cs.tau.ac.il",
      "affiliation": "Tel Aviv University, AI2",
      "google_scholar_author_page": "https://scholar.google.com/citations?hl=en&user=xCYHonIAAAAJ",
      "s2_author_page": :"https://www.semanticscholar.org/author/Jonathan-Berant/1750652",

    }
  ],
  "submission_date": "2020-10-23",
  "github_link": "https://github.com/OhadRubin/SmBop",
  "paper_link": "https://arxiv.org/abs/2010.12412",
  "allennlp_version": "2.2.0",
  "datasets": [
    {
      "name": "Spider",
      "link": "https://yale-lily.github.io/spider"
    }
  ],
  "tags": ["semantic-parsing", "text-to-sql"]
}
```

Abstract:
The de-facto standard decoding method for semantic parsing in recent years has been to autoregressively decode the abstract syntax tree of the target program using a top-down depth-first traversal. In this work, we propose an alternative approach: a Semi-autoregressive Bottom-up Parser (SmBoP) that constructs at decoding step t the top-K sub-trees of height ≤t. Our parser enjoys several benefits compared to top-down autoregressive parsing. From an efficiency perspective, bottom-up parsing allows to decode all sub-trees of a certain height in parallel, leading to logarithmic runtime complexity rather than linear. From a modeling perspective, a bottom-up parser learns representations for meaningful semantic sub-programs at each step, rather than for semantically-vacuous partial trees. We apply SmBoP on Spider, a challenging zero-shot semantic parsing benchmark, and show that SmBoP leads to a 2.2x speed-up in decoding time and a ∼5x speed-up in training time, compared to a semantic parser that uses autoregressive decoding. SmBoP obtains 71.1 denotation accuracy on Spider, establishing a new state-of-the-art, and 69.5 exact match, comparable to the 69.6 exact match of the autoregressive RAT-SQL+GraPPa.

Other details:
We were accepted to NAACL 2021

Reproducibility details:
We have a Dockerfile that deploys a demo, but it can also be used to train with minor modifications.
We also have a Google Colab demo, but it takes 5 minutes to initialize. Is it possible to host it on https://demo.allennlp.org/ ?

**Comment by epwalsh** [comment]
Thanks @OhadRubin!

> Is it possible to host it on https://demo.allennlp.org/?

It is possible, as long as it can run on CPU with a reasonable amount of memory. Would that work? How much memory does the Docker container use?

**Comment by OhadRubin** [comment]
I got it working on google colab with no gpu, it uses around 5GB of RAM. I guess on docker it wouldn't be any different because the code is almost the same.
It is however kinda slow to perform inference with... Will it be faster on your cluster?

**Comment by epwalsh** [comment]
5GB is fine. How slow are we talking about though?

**Comment by OhadRubin** [comment]
7.5 seconds compared to almost instantly on a gpu.

**Comment by epwalsh** [comment]
Hmm that's not ideal, and we'd like to avoid using a GPU due to the costs. @dirkgr, @schmmd, @codeviking would you like to weight in? Is ~7.5 seconds an okay response time?

**Comment by dirkgr** [comment]
If it’s 7.5s on a typical input, and not an unrealistically short one, I
think it’s OK to get started, but we’re going to have to solve this problem
at some point.

**Comment by schmmd** [comment]
7.5s is "pushing it" but it's not "out of the question".

**Comment by OhadRubin** [comment]
Cool, so how do we proceed?

**Comment by epwalsh** [comment]
@OhadRubin I guess we'd need to figure out the front-end. What would the inputs be? A query and a table, or just a query? And what would the outputs be? Just the raw SQL or also the result of executing the SQL?

**Comment by OhadRubin** [comment]
I think it should be very similar to this demo [here](https://colab.research.google.com/drive/1KGlETGn9wngUPQrkFfa7ySecU-t_I3Y2#scrollTo=X1v6F3TlOMKH). Where the user picks out of a dropdown menu a schema from Spider and is shown the structure. The user inputs a natural language question where the output is raw SQL.

**Comment by epwalsh** [comment]
Thanks @OhadRubin, I'm going to continue this discussion here: https://github.com/allenai/allennlp-demo/issues/996
